name: How to portal
permalink: none

url: http://localhost:3000/

gems:
  - jekyll-archives

exclude: ["node_modules", "gulpfile.js", "package.json"]

jekyll-archives:
  enabled: [categories,tags]
  layouts:
    # year: year
    # month: month
    # day: day
    tag: tag
    category: category
  permalinks:
    # year: '/:year/'
    # month: '/:year/:month/'
    # day: '/:year/:month/:day/'
    category: '/apps/:name/'
    tag: '/themes/:name/'


# CATEGORIES
categories_info:
  gfw:
    order: 1
    title: Gfw
    description: "Description gfw"
    slug: gfw
  climate:
    order: 2
    title: Climate
    description: "Description climate"
    slug: climate
  fires:
    order: 3
    title: Fires
    description: "Description fires"
    slug: fires
  commodities:
    order: 4
    title: Commodities
    description: "Description commodities"
    slug: commodities


tags_info:
  visualize_data:
    order: 1
    title: Visualize data
    description: "Some data are produced directly by WRI and our partners, such as FORMA alerts, Intact Forest Landscapes, and some forest use data."
    slug: visualize data
  view_statistics:
    order: 2
    title: View statistics
    description: "These courses are designed to provide an in-depth understanding of the ways can support a variety of professional."
    slug: view statistics
  analyze_data:
    order: 3
    title: Analyze data
    description: "Description analyze_data"
    slug: analyze data
  suscribe_to_alerts:
    order: 4
    title: Suscribe to alerts
    description: "Description suscribe_to_alerts"
    slug: suscribe to alerts
  submit_a_story:
    order: 5
    title: Submit a story
    description: "Description submit_a_story"
    slug: submit a story
  tutorial_videos:
    order: 6
    title: Tutorial videos
    description: "Description tutorial_videos"
    slug: tutorial videos
  webinars:
    order: 7
    title: Webinars
    description: "Description webinars"
    slug: webinars
  training_modules:
    order: 8
    title: Training modules
    description: "Description training_modules"
    slug: training modules
